### ISSUE TITLE
Accumulated delay error in time estimates

### ISSUE THREAD

**Issue by andresperezEUT** [sharathadavanne/multiple-target-tracking#1]
When running the example script, the temporal estimates of the particles seem to have a cummulative delay (the higher the time index, the bigger the delay/error magnitude), producing wrong estimates.
I'm attaching the plots of the azimuth and elevation estimates, for the moving source example. The timing mismatch is observed in the variable `Times` (l. 168); it is not a visualization error.
The script was run with default parameters.
![result_azi](https://user-images.githubusercontent.com/1895237/84068976-13450600-a9ca-11ea-8773-0a790055d9a5.jpg)
![result_ele](https://user-images.githubusercontent.com/1895237/84068987-17712380-a9ca-11ea-89f7-a35cef75cca9.jpg)

**Comment by sharathadavanne** [comment]
Hi @andresperezlopez thanks for checking this repo. I want to just confirm, you got the above results by running the code without any changes? or did you use the Times variable as the x-variable for plot function?

**Comment by andresperezEUT** [comment]
The code was run without any changes, from the last commit on the master branch.
From my understanding, though, in lines 185:188
```
            t = Times{j,ind};
            m = SM{j,ind};

            h=plot(t,m(isazi,:),'g-');
```
looks like the `Times` variable is actually used as the x-variable.

**Comment by leomccormack** [comment]
Hi, I just sent a pull request which should rectify this issue. However, please let me know if more is needed : )

**Comment by sharathadavanne** [comment]
Thanks for the quick-fix @leomccormack

**Comment by andresperezEUT** [comment]
thanks!
